- name: Ensure node_exporter group
  ansible.builtin.group:
    name: node_exporter
    system: true

- name: Ensure node_exporter user
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    shell: /usr/sbin/nologin
    system: true

- name: Download node_exporter checksum file
  ansible.builtin.uri:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt"
    return_content: true
  register: node_exporter_checksum_file

- name: Parse node_exporter checksum
  ansible.builtin.set_fact:
    node_exporter_checksum: >-
      {{ (node_exporter_checksum_file.content.splitlines() |
         select('search', 'node_exporter-' ~ node_exporter_version ~ '.linux-amd64.tar.gz') |
         list | first).split()[0] }}

- name: Download node_exporter tar.gz {{ node_exporter_version }}
  ansible.builtin.get_url:
    url: >-
      https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: "0644"
    checksum: "sha256:{{ node_exporter_checksum }}"
  notify: Extract node_exporter

- name: Create systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: Restart node_exporter
