- name: Ensure node_exporter group & user
  group: name=node_exporter system=yes
- user:
    name: node_exporter
    group: node_exporter
    shell: /usr/sbin/nologin
    system: yes

- name: Download node_exporter checksum file
  uri:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt"
    return_content: yes
  register: node_exporter_checksum_file

- name: Parse node_exporter checksum
  set_fact:
    node_exporter_checksum: "{{ (node_exporter_checksum_file.content.splitlines() | select('search', 'node_exporter-' ~ node_exporter_version ~ '.linux-amd64.tar.gz') | list | first).split()[0] }}"

- name: Download node_exporter {{ node_exporter_version }} tar.gz
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: "0644"
    checksum: "sha256:{{ node_exporter_checksum }}"   # ✔ 무결성 검증
  register: dl_node

- name: Unpack binary
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/node_exporter
    extra_opts:
      - --strip-components=1        # 디렉터리 계층 제거
  when: dl_node.changed            # 처음 다운로드 했을 때만

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: restart node_exporter

# - meta: flush_handlers   # 즉시 핸들러 실행