# 7️⃣ World repo clone & sync ---------------------------------------------
- name: Ensure tmp clone dir exists
  ansible.builtin.file:
    path: "/opt/tmp_worlds"
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0755"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/minecraft/.ssh
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0700"

- name: Add GitHub.com to known_hosts
  ansible.builtin.known_hosts:
    path: /home/minecraft/.ssh/known_hosts
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present
    hash_host: false

- name: Check if deploy key already exists
  ansible.builtin.stat:
    path: /home/minecraft/.ssh/id_rsa_minecraft_worlds.pub
  register: key_stat

- name: Generate deploy key for GitHub (first time only)
  ansible.builtin.command:
    cmd: ssh-keygen -t rsa -b 4096 -f /home/minecraft/.ssh/id_rsa_minecraft_worlds -N '' -C ''
    creates: /home/minecraft/.ssh/id_rsa_minecraft_worlds
  become_user: minecraft
  become: true
  when: not key_stat.stat.exists
  register: github_key

- name: Show GitHub deploy key instructions (if new key)
  ansible.builtin.debug:
    msg: |
      A new SSH deploy key has been generated for the Minecraft server.

      **Next step (manual once-off):**
      1. Open your GitHub repository → *Settings* → *Deploy keys*.
      2. Click **Add deploy key**.
      3. Paste the public key(.pub), give it a name, and tick “Allow write access” if you want the server to push backups.
  when: github_key.changed or not key_stat.stat.exists

- name: Clone or pull world repository
  ansible.builtin.git:
    repo: "{{ world_repo }}"
    dest: "{{ world_repo_dir }}"
    version: "{{ world_repo_branch | default('main') }}"
    key_file: "/home/minecraft/.ssh/id_rsa_minecraft_worlds"
    update: true
    force: true
    accept_hostkey: true
  become_user: minecraft
  become: true

# -- mtime logic ----------------------------------------------------------
- name: Gather repo level.dat mtimes
  ansible.builtin.stat:
    path: "{{ world_repo_dir }}/{{ world_source_subdir }}/{{ item }}/level.dat"
  loop:
    - "{{ world_name }}"
    - "{{ world_name }}_nether"
    - "{{ world_name }}_the_end"
  register: repo_level_stats
  failed_when: false
  become_user: minecraft
  become: true

- name: Gather server level.dat mtimes
  ansible.builtin.stat:
    path: "{{ world_target_dir }}/{{ item }}/level.dat"
  loop:
    - "{{ world_name }}"
    - "{{ world_name }}_nether"
    - "{{ world_name }}_the_end"
  register: server_level_stats
  failed_when: false
  become_user: minecraft
  become: true

- name: Compute sync requirement
  ansible.builtin.set_fact:
    server_world_missing: >-
      {{ (repo_level_stats.results | zip(server_level_stats.results)
         | selectattr('0.stat.exists')
         | selectattr('1.stat.exists', 'equalto', False)
         | list | length) > 0 }}
    repo_max_mtime: >-
      {{ (repo_level_stats.results | selectattr('stat.exists')
         | map(attribute='stat.mtime') | list | default([0]) | max) | float }}
    server_max_mtime: >-
      {{ (server_level_stats.results | selectattr('stat.exists')
         | map(attribute='stat.mtime') | list | default([0]) | max) | float }}

- name: Determine if world sync is needed
  ansible.builtin.set_fact:
    do_world_sync: >-
      {{ server_world_missing or (repo_max_mtime > server_max_mtime) }}

- name: Rsync worlds into minecraft dir
  ansible.builtin.command:
    cmd: >-
      rsync -a --checksum "{{ world_repo_dir }}/{{ world_source_subdir }}/" "{{ world_target_dir }}/"
  changed_when: false
  when: do_world_sync
  delegate_to: "{{ inventory_hostname }}"  # run rsync locally on target node
  become_user: minecraft
  become: true
  notify: restart fabric

- name: Create log dir for minecraft
  ansible.builtin.file:
    path: /var/log/world_sync
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0755"

- name: Deploy world sync script with inline debug logging
  ansible.builtin.copy:
    dest: "/usr/local/bin/world_git_sync.sh"
    owner: minecraft
    group: minecraft
    mode: "0755"
    content: |
      #!/usr/bin/env bash
      exec >> /var/log/world_sync/debug.log 2>&1
      set -xeuo pipefail

      # GitHub Deploy Key 사용
      export GIT_SSH_COMMAND="ssh -i /home/minecraft/.ssh/id_rsa_minecraft_worlds -o StrictHostKeyChecking=no"

      rsync -a --checksum --delete --exclude='.git/' "{{ world_target_dir }}/{{ world_name }}/" "{{ world_repo_dir }}/{{ world_source_subdir }}/{{ world_name }}/"
      rsync -a --checksum --delete --exclude='.git/' "{{ world_target_dir }}/{{ world_name }}_nether/" "{{ world_repo_dir }}/{{ world_source_subdir }}/{{ world_name }}_nether/"
      rsync -a --checksum --delete --exclude='.git/' "{{ world_target_dir }}/{{ world_name }}_the_end/" "{{ world_repo_dir }}/{{ world_source_subdir }}/{{ world_name }}_the_end/"

      cd {{ world_repo_dir }}

      # 대상 월드 디렉터리 스테이징
      git add {{ world_source_subdir }}/{{ world_name }} \
              {{ world_source_subdir }}/{{ world_name }}_nether \
              {{ world_source_subdir }}/{{ world_name }}_the_end

      # 변경 사항이 있을 때만 커밋/푸시
      if ! git diff --cached --quiet; then
        ts=$(date +"%Y-%m-%d_%H:%M")
        git commit -m "Auto-backup $ts"
        git push origin {{ world_repo_branch }}
      fi

- name: Schedule daily world sync cron
  ansible.builtin.cron:
    name: "Daily world git push"
    user: minecraft
    minute: "{{ cron_sync_min }}"
    hour: "{{ cron_sync_hour }}"
    job: "/usr/local/bin/world_git_sync.sh >> /var/log/world_sync/sync.log 2>&1"

# ➕ Git 사용자 이름/이메일 설정을 추가 (minecraft 계정 전역에 적용)
- name: Set Git user.name and user.email for minecraft user
  become_user: minecraft
  become: true
  ansible.builtin.copy:
    dest: /home/minecraft/.gitconfig
    owner: minecraft
    group: minecraft
    mode: "0644"
    content: |
      [user]
      name = {{ git_user_name }}
      email = {{ git_user_email }}
