- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    creates: /usr/local/bin/node_exporter
    extra_opts:
      - --strip-components=1
- name: Restart node_exporter
  ansible.builtin.systemd_service:
    name: node_exporter
    daemon_reload: true
    state: restarted
    enabled: true
