- name: Gather service facts
  ansible.builtin.service_facts:

- name: Show Fabric service status
  ansible.builtin.debug:
    var: ansible_facts.services['fabric.service']

- name: Show CPU load
  ansible.builtin.command: uptime
  register: uptime_out
  changed_when: false

- name: Display load averages
  ansible.builtin.debug:
    msg: "{{ uptime_out.stdout }}"

- name: Show memory usage
  ansible.builtin.command: free -m
  register: mem_out
  changed_when: false

- name: Display memory info
  ansible.builtin.debug:
    var: mem_out.stdout_lines

- name: Show disk usage
  ansible.builtin.command: df -h /opt/minecraft
  register: disk_out
  changed_when: false

- name: Display disk info
  ansible.builtin.debug:
    var: disk_out.stdout_lines

- name: Check if port 25565 is open
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 25565
    timeout: 3
    state: started
  register: port_status
  ignore_errors: true

- name: Report port status
  ansible.builtin.debug:
    msg: "Port 25565 open: {{ port_status is not failed }}"
