- name: Restart fabric
  ansible.builtin.systemd_service:
    name: fabric
    daemon_reload: "{{ fabric_svc_changed is defined and fabric_svc_changed.changed }}"
    state: restarted
    enabled: true
